
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 19 08:10:20 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 43;
  public static final int INCREMENT = 35;
  public static final int CHAR = 50;
  public static final int CONST = 6;
  public static final int GREATEROREQUAL = 29;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int GREATER = 28;
  public static final int CONTINUE = 14;
  public static final int DECREMENT = 36;
  public static final int LESS = 30;
  public static final int FOR = 15;
  public static final int MINUS = 22;
  public static final int RPAREN = 42;
  public static final int STATIC = 16;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int BOOL = 49;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 26;
  public static final int DIV = 24;
  public static final int LESSOREQUAL = 31;
  public static final int NUM = 51;
  public static final int PLUS = 21;
  public static final int IF = 7;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 44;
  public static final int EQUAL = 34;
  public static final int LAMBDA = 47;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int INTERSECTION = 19;
  public static final int MOD = 25;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int COLON = 38;
  public static final int UNION = 17;
  public static final int LBRACE = 45;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int GOTO = 20;
  public static final int RBRACE = 46;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DIFF = 18;
  public static final int PRINT = 9;
}

